version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: adMongoDB
    ports:
      - 27017:27017
    volumes:
      - ./database:/data/db
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://127.0.0.1:27017/adDatabase